spring:
  application:
    name: movie
  datasource:
    url: jdbc:mysql://localhost:3306/object-movie?useSSL=false&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    com:
      objectbook: info